import { createServerClient } from "@supabase/ssr";
import { NextResponse, type NextRequest } from "next/server";
import {
  getSupabaseAuthCookieBaseName as getAuthCookieBaseNameForUrl,
  isDevPreviewAuthEnabled,
  isLocalAppHost,
} from "@/lib/dev-preview-auth";
import { log } from "@/lib/logger";
import {
  classifyMiddlewareRequest,
  recordServerEngagementEvent,
} from "@/lib/analytics/server-engagement";

/**
 * Read a required env var with a readable error if it's missing. Replaces the
 * old `process.env.X!` non-null assertions which crashed with a cryptic
 * `TypeError: Cannot read properties of undefined`. Once Agent 3 lands the
 * full Zod-parsed `@/lib/env` module that covers PUBLISHABLE_KEY, swap these
 * reads for `env.X`.
 */
function requireEnv(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(`Missing required environment variable: ${name}`);
  }
  return value;
}

/**
 * Public-path table. Each entry intentionally bypasses the Supabase session
 * check so that unauthenticated callers receive the route's own response
 * instead of being 307-redirected to /lobby.
 *
 * `prefix: true` means the path itself AND any nested path under it are
 * public (e.g. `/lobby` matches `/lobby/onboarding` but NOT `/lobbyhack`).
 *
 * Default (no `prefix` flag) is exact match — required for paths that
 * have no real sub-routes, so we don't accidentally auth-bypass a future
 * `/termsfake` style route.
 *
 *   /lobby               — prefix: entry point + onboarding sub-routes.
 *   /terms               — exact: marketing page only.
 *   /privacy             — exact: marketing page only.
 *   /pricing             — exact: marketing page only.
 *   /waitlist            — exact: marketing page only.
 *   /opengraph-image     — exact: social preview image generated by Next.js.
 *   /api/auth/callback   — exact: Supabase OAuth callback runs pre-session.
 *   /api/auth/google/start — exact: first-party Google login kickoff.
 *   /api/auth/signout    — exact: must be able to clear stale/expired sessions.
 *   /api/dev/preview-login — exact: local-only stub login for product review.
 *   /api/gmail/callback  — exact: Gmail connect callback and Google login return.
 *   /api/stripe/webhook  — exact: Stripe POSTs unauthenticated;
 *                                redirect would break billing (audit M-9 / P2-1).
 *   /api/cron            — prefix: Vercel Cron POSTs sans session;
 *                                cron routes self-auth via verifyCronAuth().
 */
const PUBLIC_PATHS: ReadonlyArray<{ path: string; prefix?: boolean }> = [
  { path: "/lobby", prefix: true },
  { path: "/terms" },
  { path: "/privacy" },
  { path: "/pricing" },
  { path: "/waitlist" },
  // PR 5 marketing surfaces — public landing pages with their own
  // CTAs. /season-pass + /campus must be reachable without a session
  // so an unauthenticated visitor can read the pitch and decide.
  { path: "/season-pass" },
  { path: "/campus" },
  { path: "/campus/actions", prefix: true },
  { path: "/opengraph-image" },
  { path: "/api/auth/callback" },
  { path: "/api/auth/google/start" },
  { path: "/api/auth/signout" },
  { path: "/api/dev/preview-login" },
  { path: "/api/gmail/callback" },
  { path: "/api/stripe/webhook" },
  { path: "/api/cron", prefix: true },
];

/**
 * Decide whether `pathname` is reachable without a Supabase session.
 *
 * Exact entries match only the literal path. Prefix entries match the path
 * itself and any nested sub-path under a `/` boundary — so `/lobby` and
 * `/lobby/onboarding` are public, but `/lobbyhack` is NOT.
 *
 * Exported for unit testing.
 */
export function isPathPublic(pathname: string): boolean {
  return PUBLIC_PATHS.some(({ path, prefix }) =>
    prefix
      ? pathname === path || pathname.startsWith(path + "/")
      : pathname === path,
  );
}

export async function updateSession(request: NextRequest) {
  let supabaseResponse = NextResponse.next({
    request,
  });

  // Visibility: prove the middleware runs on each request in Vercel logs.
  // Path only — never log the full request (privacy + log volume).
  log.debug("middleware.updateSession", { path: request.nextUrl.pathname });

  const authCookieBaseName = getSupabaseAuthCookieBaseName();
  if (hasMalformedAuthCookie(request.cookies.getAll(), authCookieBaseName)) {
    log.warn("middleware.malformed_auth_cookie", {
      path: request.nextUrl.pathname,
    });
    const response = !isPathPublic(request.nextUrl.pathname)
      ? unauthenticatedResponse(request)
      : NextResponse.next({ request });
    clearAuthCookies(response, authCookieBaseName);
    return response;
  }

  const publicPath = isPathPublic(request.nextUrl.pathname);
  if (
    !publicPath &&
    shouldUseDevPreviewLogin(request) &&
    !readAuthCookieValue(request.cookies.getAll(), authCookieBaseName)
  ) {
    return devPreviewLoginResponse(request);
  }

  if (publicPath && !isLobbyRoot(request.nextUrl.pathname)) {
    fireEngagement(request, { isAuthenticated: false, userId: null });
    return supabaseResponse;
  }

  const supabase = createServerClient(
    requireEnv("NEXT_PUBLIC_SUPABASE_URL"),
    requireEnv("NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY"),
    {
      cookies: {
        getAll() {
          return request.cookies.getAll();
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value }) =>
            request.cookies.set(name, value),
          );
          supabaseResponse = NextResponse.next({
            request,
          });
          cookiesToSet.forEach(({ name, value, options }) =>
            supabaseResponse.cookies.set(name, value, options),
          );
        },
      },
    },
  );

  // Refresh session — this is critical for token refresh to work. Supabase
  // Auth can occasionally return a non-JSON edge error; treat that as no
  // reliable session so public routes still render and private routes fall
  // back to the Lobby instead of hanging on the loading shell.
  const user = await readMiddlewareUser(supabase, request.nextUrl.pathname);

  if (!user && !publicPath) {
    fireEngagement(request, { isAuthenticated: false, userId: null });
    if (shouldUseDevPreviewLogin(request)) {
      return devPreviewLoginResponse(request);
    }
    return unauthenticatedResponse(request);
  }

  fireEngagement(request, {
    isAuthenticated: user != null,
    userId: user?.id ?? null,
  });

  return supabaseResponse;
}

/**
 * Fire-and-forget engagement event emission. Classifies the request, and
 * if a classification is returned, writes via the service-role helper.
 * Never throws, never awaits — safe to call before any return statement.
 *
 * The helper is a no-op when `TOWER_SERVER_ANALYTICS_ENABLED !== "1"`, so
 * the dynamic admin-client import never runs in environments where the
 * kill-switch is off (dev, tests, preview deployments without the flag).
 */
function fireEngagement(
  request: NextRequest,
  authState: { isAuthenticated: boolean; userId: string | null },
): void {
  const classification = classifyMiddlewareRequest({
    pathname: request.nextUrl.pathname,
    method: request.method,
    userAgent: request.headers.get("user-agent"),
    prefetch: request.headers.get("next-router-prefetch"),
    rsc: request.headers.get("rsc"),
    secFetchDest: request.headers.get("sec-fetch-dest"),
    isAuthenticated: authState.isAuthenticated,
  });

  if (!classification) return;

  void recordServerEngagementEvent({
    eventType: classification.eventType,
    pathname: classification.pathname,
    userId: authState.userId,
    floor: classification.floor,
    metadata: { is_authenticated: authState.isAuthenticated },
  }).catch(() => {});
}

function getSupabaseAuthCookieBaseName(): string {
  return getAuthCookieBaseNameForUrl(
    requireEnv("NEXT_PUBLIC_SUPABASE_URL"),
  );
}

function unauthenticatedResponse(request: NextRequest): NextResponse {
  if (isApiPath(request.nextUrl.pathname)) {
    return NextResponse.json(
      { error: "Authentication required", code: "UNAUTHENTICATED" },
      { status: 401 },
    );
  }

  const url = request.nextUrl.clone();
  url.pathname = "/lobby";
  return NextResponse.redirect(url);
}

function isApiPath(pathname: string): boolean {
  return pathname === "/api" || pathname.startsWith("/api/");
}

function shouldUseDevPreviewLogin(request: NextRequest): boolean {
  return (
    isDevPreviewAuthEnabled() &&
    isLocalAppHost(request.nextUrl.hostname) &&
    !isApiPath(request.nextUrl.pathname)
  );
}

function devPreviewLoginResponse(request: NextRequest): NextResponse {
  const url = request.nextUrl.clone();
  url.pathname = "/api/dev/preview-login";
  url.search = "";
  url.searchParams.set(
    "next",
    `${request.nextUrl.pathname}${request.nextUrl.search}`,
  );
  return NextResponse.redirect(url);
}

function hasMalformedAuthCookie(
  cookies: Array<{ name: string; value: string }>,
  baseName: string,
): boolean {
  const value = readAuthCookieValue(cookies, baseName);
  if (!value) return false;
  try {
    const decoded = value.startsWith("base64-")
      ? decodeBase64Url(value.slice("base64-".length))
      : value;
    const parsed = JSON.parse(decoded) as unknown;
    return !parsed || typeof parsed !== "object" || Array.isArray(parsed);
  } catch {
    return true;
  }
}

function readAuthCookieValue(
  cookies: Array<{ name: string; value: string }>,
  baseName: string,
): string | null {
  const exact = cookies.find((cookie) => cookie.name === baseName);
  if (exact) return exact.value;

  const chunks: string[] = [];
  for (let i = 0; i < 5; i += 1) {
    const chunk = cookies.find((cookie) => cookie.name === `${baseName}.${i}`);
    if (!chunk) break;
    chunks.push(chunk.value);
  }
  return chunks.length > 0 ? chunks.join("") : null;
}

function decodeBase64Url(value: string): string {
  const normalized = value.replace(/-/g, "+").replace(/_/g, "/");
  const padded = normalized.padEnd(
    normalized.length + ((4 - (normalized.length % 4)) % 4),
    "=",
  );
  return atob(padded);
}

function clearAuthCookies(response: NextResponse, baseName: string): void {
  const options = { path: "/", maxAge: 0 };
  response.cookies.set(baseName, "", options);
  for (let i = 0; i < 5; i += 1) {
    response.cookies.set(`${baseName}.${i}`, "", options);
  }
}

async function readMiddlewareUser(
  supabase: ReturnType<typeof createServerClient>,
  pathname: string,
) {
  try {
    const {
      data: { user },
    } = await supabase.auth.getUser();
    return user;
  } catch (err) {
    log.warn("middleware.auth_get_user_failed", {
      path: pathname,
      error: err instanceof Error ? err.message : String(err),
    });
    return null;
  }
}

/** Match `/lobby` and `/lobby/` — not nested sub-paths. */
function isLobbyRoot(pathname: string): boolean {
  return pathname === "/lobby" || pathname === "/lobby/";
}
