// Generated by foundry. Slot: lobby/otis/regular/idle
import type { JSX } from "react";

export function OtisCharacter(): JSX.Element {
  return (
    <img
      src="/art/lobby/otis/regular/idle.webp"
      alt="Otis the concierge, idle pose"
      role="img"
      width={170}
      height={290}
      loading="lazy"
      decoding="async"
    />
  );
}
