-- =============================================================================
-- Migration 0006 — Reconcile schema with live DB after rebase
--
-- Three concerns, ALL made idempotent so this can safely run against any
-- environment (live prod where some artifacts already exist, or a clean DB):
--
--   1. CREATE stripe_webhook_events — already created via
--      src/db/manual/003_stripe_webhook_events.sql. Wrap in IF NOT EXISTS.
--   2. DROP stripe_events — was never actually created in prod (my session-23
--      migration that would have created it was dropped during conflict
--      resolution in favor of the better stripe_webhook_events). Wrap in
--      IF EXISTS so prod (which lacks the table) doesn't error.
--   3. ADD COLUMN to daily_snapshots — legitimate new columns for richer
--      CFO analytics (conversion_rate, status counts). These do not exist
--      in prod and need to be added. Wrap in IF NOT EXISTS for safety.
--
-- Generated by drizzle-kit, manually hardened to be idempotent.
-- =============================================================================

CREATE TABLE IF NOT EXISTS "stripe_webhook_events" (
	"id" text PRIMARY KEY NOT NULL,
	"type" text NOT NULL,
	"livemode" boolean DEFAULT false NOT NULL,
	"received_at" timestamp with time zone DEFAULT now() NOT NULL,
	"processed_at" timestamp with time zone,
	"status" text DEFAULT 'received' NOT NULL,
	"error" text,
	"payload" jsonb
);
--> statement-breakpoint
DROP TABLE IF EXISTS "stripe_events" CASCADE;
--> statement-breakpoint
ALTER TABLE "daily_snapshots" ADD COLUMN IF NOT EXISTS "conversion_rate" numeric(5, 2);
--> statement-breakpoint
ALTER TABLE "daily_snapshots" ADD COLUMN IF NOT EXISTS "stale_count" integer;
--> statement-breakpoint
ALTER TABLE "daily_snapshots" ADD COLUMN IF NOT EXISTS "applied_count" integer;
--> statement-breakpoint
ALTER TABLE "daily_snapshots" ADD COLUMN IF NOT EXISTS "screening_count" integer;
--> statement-breakpoint
ALTER TABLE "daily_snapshots" ADD COLUMN IF NOT EXISTS "interview_count" integer;
--> statement-breakpoint
ALTER TABLE "daily_snapshots" ADD COLUMN IF NOT EXISTS "offer_count" integer;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_stripe_webhook_events_type_received" ON "stripe_webhook_events" USING btree ("type","received_at" DESC NULLS LAST);
