import type { ArtLabAssetPackManifest } from "./manifest.schema";

export interface RenderArtLabIntegrationSnippetOptions {
  format?: "tsx";
}

/**
 * Code-injection defence for fields interpolated into generated TSX.
 *
 * `m.accessibility.altText`, `gsapCues[].targetSelector`, and
 * `gsapCues[].easing` arrive as `z.string().min(1)` from the manifest
 * schema (no character allow-list), so an attacker who controls a
 * manifest could otherwise supply `altText: 'x" onerror="alert(1)'` or
 * `easing: '); evil(); ('` and have those bytes spliced straight into
 * the JSX as attribute breakers / expression breakers.
 *
 * `JSON.stringify` on a string always produces a single, properly-escaped
 * double-quoted JS string literal: any embedded `"` becomes `\"`, any
 * `\n` becomes `\\n`, etc. So `alt={JSON.stringify(value)}` is safe in
 * JSX attribute position, `fromTo(${JSON.stringify(value)}, ...)` is
 * safe in JS argument position, and the output for benign strings
 * (`"Otis the concierge, idle pose"`) is byte-identical to the previous
 * bare-quote form, so existing golden snapshots stay stable.
 *
 * Identifiers (`component`, `cueId`) are validated as
 * `^[a-zA-Z_$][a-zA-Z0-9_$]*$` in the schema, so this renderer can
 * splice them in raw without re-validating.
 */
function quote(value: string): string {
  return JSON.stringify(value);
}

function publicSrcFor(appPath: string): string {
  if (!appPath.startsWith("public/")) {
    throw new Error(`renderArtLabIntegrationSnippet: appPath outside public/: ${appPath}`);
  }
  return appPath.replace(/^public/, "");
}

function characterSpriteImg(m: ArtLabAssetPackManifest): string {
  const component = m.intendedSlot.component ?? "ArtLabSprite";
  return [
    `// Generated by ArtLab SDK. Slot: ${m.intendedSlot.slotId}`,
    `import type { JSX } from "react";`,
    ``,
    `export function ${component}(): JSX.Element {`,
    `  return (`,
    `    <img`,
    `      src=${quote(publicSrcFor(m.intendedSlot.appPath))}`,
    `      alt=${quote(m.accessibility.altText)}`,
    `      role=${quote(m.accessibility.role)}`,
    `      width={${m.dimensions.displayWidthPx}}`,
    `      height={${m.dimensions.displayHeightPx}}`,
    `      loading="lazy"`,
    `      decoding="async"`,
    `    />`,
    `  );`,
    `}`,
  ].join("\n");
}

function characterSpriteGsap(m: ArtLabAssetPackManifest): string {
  const component = m.intendedSlot.component ?? "ArtLabSprite";
  const cueLines = m.gsapCues
    .map(
      (c) =>
        `      const tl_${c.cueId} = gsap.timeline(); tl_${c.cueId}.fromTo(${quote(c.targetSelector)}, {opacity:0}, {opacity:1, duration: ${c.durationMs / 1000}, ease: ${quote(c.easing)}}); timelines.push(tl_${c.cueId});`,
    )
    .join("\n");
  return [
    `// Generated by ArtLab SDK. Slot: ${m.intendedSlot.slotId} (GSAP-animated)`,
    `"use client";`,
    `import { useEffect, useRef } from "react";`,
    `import type { JSX } from "react";`,
    `import { gsap } from "@/lib/gsap-init";`,
    ``,
    `export function ${component}(): JSX.Element {`,
    `  const ref = useRef<HTMLImageElement | null>(null);`,
    `  useEffect(() => {`,
    `    const timelines: gsap.core.Timeline[] = [];`,
    cueLines,
    `    return () => { for (const t of timelines) t.kill(); };`,
    `  }, []);`,
    `  return (`,
    `    <img`,
    `      ref={ref}`,
    `      data-otis`,
    `      src=${quote(publicSrcFor(m.intendedSlot.appPath))}`,
    `      alt=${quote(m.accessibility.altText)}`,
    `      role=${quote(m.accessibility.role)}`,
    `      width={${m.dimensions.displayWidthPx}}`,
    `      height={${m.dimensions.displayHeightPx}}`,
    `      loading="lazy"`,
    `      decoding="async"`,
    `    />`,
    `  );`,
    `}`,
  ].join("\n");
}

const TEMPLATE_RENDERERS: Record<string, (m: ArtLabAssetPackManifest) => string> = {
  "character-sprite-img": characterSpriteImg,
  "character-sprite-gsap": characterSpriteGsap,
};

export function renderArtLabIntegrationSnippet(
  manifest: ArtLabAssetPackManifest,
  _opts: RenderArtLabIntegrationSnippetOptions = {},
): string {
  const renderer = TEMPLATE_RENDERERS[manifest.integrationSnippetTemplate];
  if (!renderer) {
    throw new Error(
      `renderArtLabIntegrationSnippet: unknown template "${manifest.integrationSnippetTemplate}"`,
    );
  }
  return renderer(manifest);
}

export const ARTLAB_INTEGRATION_SNIPPET_TEMPLATES = Object.keys(TEMPLATE_RENDERERS);
