/**
 * Structured interview prep packet generation.
 *
 * Replaces the prior hardcoded markdown template (with generic real-estate
 * questions baked in) with a schema-validated, company- and role-specific
 * packet generated by the LLM.
 *
 * Output is marshalled back to a markdown body before persisting so the
 * existing Briefing Room viewer keeps working — same string contract.
 */

import { generateText, Output } from "ai";
import { z } from "zod/v4";
import { getAgentModel, getActiveModelId } from "@/lib/ai/model";
import { getCachedSystem } from "@/lib/ai/prompt-cache";
import { recordAgentRun } from "@/lib/ai/telemetry";

// ---------------------------------------------------------------------------
// Schema
// ---------------------------------------------------------------------------
const QuestionWithSTAR = z.object({
  q: z.string().max(220).describe("The interview question, phrased exactly as it'd be asked."),
  suggested_star_outline: z
    .string()
    .max(450)
    .describe(
      "One-sentence STAR-framework outline suggesting how the user should structure their answer (Situation → Task → Action → Result). Reference relevant elements of the user's likely background.",
    ),
});

const QuestionWithHint = z.object({
  q: z.string().max(220).describe("The interview question."),
  hint: z
    .string()
    .max(450)
    .describe(
      "A direct-answer hint or framework. For technical questions, sketch the structure of a strong response without writing the entire answer for the user.",
    ),
});

export const PrepPacketSchema = z.object({
  company_summary: z
    .string()
    .max(900)
    .describe(
      "3-5 sentence overview of the company specific to this interview — business model, recent strategic moves, competitive positioning. Cite specifics.",
    ),
  role_summary: z
    .string()
    .max(700)
    .describe(
      "What this specific role does, who it reports to, what success looks like in the first 90 days.",
    ),
  behavioral_questions: z
    .array(QuestionWithSTAR)
    .min(3)
    .max(6)
    .describe(
      "Likely behavioral questions for this company + role. Each with a STAR-framework outline.",
    ),
  technical_questions: z
    .array(QuestionWithHint)
    .min(2)
    .max(6)
    .describe(
      "Likely role-specific / technical questions. Each with a direct-answer hint.",
    ),
  questions_to_ask: z
    .array(z.string().max(220))
    .min(3)
    .max(6)
    .describe(
      "Sharp questions the candidate should ask the interviewer — specific to this company's recent moves or this role's unique context.",
    ),
  red_flags: z
    .array(z.string().max(220))
    .max(4)
    .describe(
      "Optional: things to watch for during the interview that might indicate a culture / fit problem at this company. Empty array if none.",
    ),
});

export type PrepPacket = z.infer<typeof PrepPacketSchema>;

// ---------------------------------------------------------------------------
// Renderer — typed object → markdown body
// ---------------------------------------------------------------------------
export function renderPrepPacket(
  packet: PrepPacket,
  meta: {
    companyName: string;
    role: string;
    interviewFormat?: string;
    interviewRound?: string;
  },
): string {
  const formatLine =
    meta.interviewFormat && meta.interviewFormat !== "general"
      ? `\n**Interview Format:** ${meta.interviewFormat
          .replace("_", " ")
          .replace(/\b\w/g, (c) => c.toUpperCase())}`
      : "";
  const roundLine = meta.interviewRound ? `\n**Round:** ${meta.interviewRound}` : "";

  const behavioralLines = packet.behavioral_questions
    .map(
      (q, i) =>
        `${i + 1}. **${q.q}**\n   *Framework: ${q.suggested_star_outline}*`,
    )
    .join("\n\n");

  const technicalLines = packet.technical_questions
    .map((q, i) => `${i + 1}. **${q.q}**\n   *${q.hint}*`)
    .join("\n\n");

  const askLines = packet.questions_to_ask
    .map((q, i) => `${i + 1}. "${q}"`)
    .join("\n");

  const redFlagSection =
    packet.red_flags.length > 0
      ? `\n---\n\n## 7. Watch For\n${packet.red_flags.map((f) => `- ${f}`).join("\n")}\n`
      : "";

  const generated = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return `# Interview Prep Packet — ${meta.companyName}
**Role:** ${meta.role}${formatLine}${roundLine}
**Generated:** ${generated}

---

## 1. Company Overview
${packet.company_summary}

---

## 2. Role Summary
${packet.role_summary}

---

## 3. Likely Questions — Behavioral (STAR Framework)

${behavioralLines}

---

## 4. Likely Questions — Role-Specific / Technical

${technicalLines}

---

## 5. Questions to Ask Them (Pick 2-3)
${askLines}

---

## 6. Day-Of Reminders
- Review this packet the night before — don't cram morning of
- Have 2-3 STAR stories ready that can flex across multiple questions
- Arrive mentally fresh. Confidence > perfection.
- Have your questions ready. Not asking questions is a red flag.${redFlagSection}`;
}

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------
const SYSTEM_PROMPT = `You are the CPO of The Tower — a methodical interview-prep specialist. You build prep packets that are company-specific and role-specific. You never produce generic templates.

For every prep packet you must:
  - Write a company_summary that mentions the specific business model and at least one recent strategic move (acquisition, restructure, hire, expansion).
  - Write a role_summary that nails what the role actually does at THIS company.
  - Generate 3-6 behavioral questions tailored to this company's known interview style (e.g. PE shops grill on deal experience; CRE firms grill on market awareness).
  - Generate 2-6 technical / role-specific questions with direct-answer hints.
  - Generate 3-6 sharp questions the candidate can ASK the interviewer.
  - Optional: red_flags to watch for during the interview (max 4).

Use the STAR framework on behavioral questions (Situation, Task, Action, Result). Be specific. Generic = bad packet.`;

interface GenerateInput {
  userId: string;
  companyName: string;
  role: string;
  interviewFormat?: string;
  interviewRound?: string;
  /** Optional — pulled from CIO research database when available. */
  companyResearch?: string;
}

export async function generateStructuredPrepPacket(
  input: GenerateInput,
): Promise<{ packet: PrepPacket; markdown: string } | null> {
  const start = Date.now();
  const modelId = getActiveModelId();

  const researchBlock = input.companyResearch
    ? `\n\nCOMPANY RESEARCH (use this — don't invent specifics):\n${input.companyResearch.slice(0, 1500)}`
    : "";

  const formatHint =
    input.interviewFormat && input.interviewFormat !== "general"
      ? ` (${input.interviewFormat.replace("_", " ")})`
      : "";
  const roundHint = input.interviewRound ? ` — ${input.interviewRound}` : "";

  const prompt = `Build a prep packet for ${input.companyName} — ${input.role}${formatHint}${roundHint}.${researchBlock}

The user has the interview soon. Make every question and every framework specific. No filler.`;

  try {
    const result = await generateText({
      model: getAgentModel(),
      system: getCachedSystem(SYSTEM_PROMPT),
      prompt,
      output: Output.object({ schema: PrepPacketSchema }),
    });

    if (!result.output) return null;

    void recordAgentRun({
      userId: input.userId,
      agent: "cpo",
      action: "structured.prep_packet",
      modelId,
      usage: result.usage,
      durationMs: Date.now() - start,
      inputSummary: `${input.companyName} / ${input.role}`,
      outputSummary: `${result.output.behavioral_questions.length}b/${result.output.technical_questions.length}t questions`,
    });

    return {
      packet: result.output,
      markdown: renderPrepPacket(result.output, {
        companyName: input.companyName,
        role: input.role,
        interviewFormat: input.interviewFormat,
        interviewRound: input.interviewRound,
      }),
    };
  } catch (err) {
    void recordAgentRun({
      userId: input.userId,
      agent: "cpo",
      action: "structured.prep_packet",
      modelId,
      usage: undefined,
      durationMs: Date.now() - start,
      inputSummary: `${input.companyName} / ${input.role}`,
      outputSummary: null,
      error: err instanceof Error ? err.message : String(err),
      status: "failed",
    });
    return null;
  }
}
