#!/bin/bash
# === Phase 1 Local Setup Script ===
# Run from project root: bash scripts/setup-env.sh

set -e

ENV_FILE=".env.local"

if [ -f "$ENV_FILE" ]; then
  echo "⚠️  $ENV_FILE already exists. Backing up to .env.local.bak"
  cp "$ENV_FILE" "${ENV_FILE}.bak"
fi

cat > "$ENV_FILE" << 'EOF'
# === The Tower — Environment Variables ===
# Auto-generated by setup-env.sh. NEVER commit this file.

# --- Phase 0: Foundation ---
NEXT_PUBLIC_SUPABASE_URL=https://jzrsrruugcajohvvmevg.supabase.co
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6cnNycnV1Z2Nham9odnZtZXZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4NjM5MTgsImV4cCI6MjA4OTQzOTkxOH0.OKidbRgCqne8Bc_YrUuWMCX6KWsq8uQ0_A_s0e1dYKc
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6cnNycnV1Z2Nham9odnZtZXZnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3Mzg2MzkxOCwiZXhwIjoyMDg5NDM5OTE4fQ.MTxBQzU4JTT_dr1625OnyMAKMyAxD7xTGr4YK0QrsjM
SUPABASE_DB_URL=postgresql://postgres:9UC04VSx8ODIVPJF@db.jzrsrruugcajohvvmevg.supabase.co:5432/postgres

# Google OAuth (configured in Supabase dashboard)
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

# --- Phase 1: Agents ---
# Get yours at: https://console.anthropic.com/settings/keys
ANTHROPIC_API_KEY=
EOF

echo "✅ Created $ENV_FILE"
echo ""
echo "⚠️  NEXT STEPS:"
echo "  1. Add your ANTHROPIC_API_KEY to $ENV_FILE"
echo "  2. Run the Phase 1 migration SQL in Supabase SQL Editor"
echo "     → Open: https://supabase.com/dashboard/project/jzrsrruugcajohvvmevg/sql/new"
echo "     → Paste contents of: scripts/phase1-migration.sql"
echo "  3. Run: npx drizzle-kit push"
echo "  4. Run: npm run dev"
