import type { FoundryAssetPackManifest } from "./manifest.schema";

export interface RenderFoundryIntegrationSnippetOptions {
  format?: "tsx";
}

function publicSrcFor(appPath: string): string {
  if (!appPath.startsWith("public/")) {
    throw new Error(`renderFoundryIntegrationSnippet: appPath outside public/: ${appPath}`);
  }
  return appPath.replace(/^public/, "");
}

function characterSpriteImg(m: FoundryAssetPackManifest): string {
  const component = m.intendedSlot.component ?? "FoundrySprite";
  return [
    `// Generated by foundry. Slot: ${m.intendedSlot.slotId}`,
    `import type { JSX } from "react";`,
    ``,
    `export function ${component}(): JSX.Element {`,
    `  return (`,
    `    <img`,
    `      src="${publicSrcFor(m.intendedSlot.appPath)}"`,
    `      alt="${m.accessibility.altText}"`,
    `      role="${m.accessibility.role}"`,
    `      width={${m.dimensions.displayWidthPx}}`,
    `      height={${m.dimensions.displayHeightPx}}`,
    `      loading="lazy"`,
    `      decoding="async"`,
    `    />`,
    `  );`,
    `}`,
  ].join("\n");
}

function characterSpriteGsap(m: FoundryAssetPackManifest): string {
  const component = m.intendedSlot.component ?? "FoundrySprite";
  const cueLines = m.gsapCues
    .map(
      (c) =>
        `      const tl_${c.cueId} = gsap.timeline(); tl_${c.cueId}.fromTo("${c.targetSelector}", {opacity:0}, {opacity:1, duration: ${c.durationMs / 1000}, ease: "${c.easing}"}); timelines.push(tl_${c.cueId});`,
    )
    .join("\n");
  return [
    `// Generated by foundry. Slot: ${m.intendedSlot.slotId} (GSAP-animated)`,
    `"use client";`,
    `import { useEffect, useRef } from "react";`,
    `import type { JSX } from "react";`,
    `import { gsap } from "@/lib/gsap-init";`,
    ``,
    `export function ${component}(): JSX.Element {`,
    `  const ref = useRef<HTMLImageElement | null>(null);`,
    `  useEffect(() => {`,
    `    const timelines: gsap.core.Timeline[] = [];`,
    cueLines,
    `    return () => { for (const t of timelines) t.kill(); };`,
    `  }, []);`,
    `  return (`,
    `    <img`,
    `      ref={ref}`,
    `      data-otis`,
    `      src="${publicSrcFor(m.intendedSlot.appPath)}"`,
    `      alt="${m.accessibility.altText}"`,
    `      role="${m.accessibility.role}"`,
    `      width={${m.dimensions.displayWidthPx}}`,
    `      height={${m.dimensions.displayHeightPx}}`,
    `      loading="lazy"`,
    `      decoding="async"`,
    `    />`,
    `  );`,
    `}`,
  ].join("\n");
}

const TEMPLATE_RENDERERS: Record<string, (m: FoundryAssetPackManifest) => string> = {
  "character-sprite-img": characterSpriteImg,
  "character-sprite-gsap": characterSpriteGsap,
};

export function renderFoundryIntegrationSnippet(
  manifest: FoundryAssetPackManifest,
  _opts: RenderFoundryIntegrationSnippetOptions = {},
): string {
  const renderer = TEMPLATE_RENDERERS[manifest.integrationSnippetTemplate];
  if (!renderer) {
    throw new Error(
      `renderFoundryIntegrationSnippet: unknown template "${manifest.integrationSnippetTemplate}"`,
    );
  }
  return renderer(manifest);
}

export const FOUNDRY_INTEGRATION_SNIPPET_TEMPLATES = Object.keys(TEMPLATE_RENDERERS);
